---
title: "Traitement des données du RA"
author: "Jean-Baptiste Paroissien"
date: "26/10/2016"
output: html_notebook
fig_caption: yes
highlight: zenburn
number_sections: yes
theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/media/sf_GIS_ED/Dev/")
# Chargement des librairies
library(RODBC);library(gdata);library(rgrass7);library(fields);library(geoR);library(stringr);library(ggplot2);library(plotly);library(rgdal);library(maptools);library(RColorBrewer);library(classInt);library(devtools);
library(Hmisc);library(gridExtra);library(mapproj);library(wesanderson);library(data.table);library(FactoMineR);library(knitr)

# Définition des principaux répertoires de travail
repLucas <- "/media/sf_GIS_ED/Dev/Data/Lucas/"
repCLC <- "/media/sf_GIS_ED/Dev/Data/CLC/"
repBase <- "/media/sf_GIS_ED/Dev/Data/Base/"
repagreste <- "/media/sf_GIS_ED/Dev/Data/Vegetation_Occup/Agreste/Disar/"
# Mise en place de la connexion ODBC
loc <- odbcConnect("solelevage",case="postgresql", believeNRows=FALSE)

# Fonction très pratique pour remplacer une suite de charact?res par une autre
gsub2 <- function(pattern, replacement, x, ...) {
  for(i in 1:length(pattern))
    x <- gsub(pattern[i], replacement[i], x, ...)
  x
}
```

# Représentation cartographique de variables associées à l'activité de l'élevage

## L'occupation du sol

### A l'échelle de la france
```{r,highlight=TRUE,eval=FALSE}
# Configuration de la connexion vers le PostGIS
dsn <- "PG:dbname='sol_elevage' host='localhost' port='5432' user='jb'"

# Lecture du postgis
# ogrListLayers(dsn) # Pour connaître la liste des PostGIS de la BDD
mapcanton <- readOGR(dsn = dsn, "canton")

p_variable <- "var_sth7910"
l_variable <- "Evolution de la STH 1979-2010 (%) "
# ggplot2
gpclibPermit()
carto <- fortify(mapcanton, region="id_geofla")

# Jointure et changement de nom
carto <- merge(carto, mapcanton@data[,c("id_geofla",p_variable)], by.x="id", by.y="id_geofla")
colnames(carto)[8] <- "fill"
  
# Classement (pour faciliter l'interprétation, voir pour obtenir une même classe de valeur par période pour les 4 cartes)
# Extraction de la légende (en horizontal) # Se débrouiller pour partir de 0/Problème dans le classement lorsque l'on part de 1979...certaines valeurs ne sont plus représentées avec les autres années
classe_valeur <- round(classIntervals(carto[,"fill"],n=5,style="quantile",digits=2,na.rm=TRUE)[[2]],0)
carto[,"fill"] <- cut(carto[,"fill"] ,breaks = data.frame(classe_valeur)[,1],include.lowest=T)  

p1 <- ggplot(carto, aes(x=long, y=lat)) +  geom_polygon(data=carto, aes(group=group, fill=fill)) + scale_fill_brewer(palette = "YlOrBr",name=paste(l_variable,sep=""),guide = guide_legend(reverse=TRUE,nrow=1))+theme(legend.position="bottom")#+guides(colour = guide_legend(nrow = 1))

ggsave(p1, file = paste("map_",p_variable,".png",sep=""), width = 7, height = 7)  

```



```{r,highlight=TRUE,eval=FALSE}
# Configuration de la connexion vers le PostGIS
dsn <- "PG:dbname='sol_elevage' host='localhost' port='5432' user='jb'"

# Sélection de la région d'étude 
reg <- "54" #54pour région Poitou Charentes 

# Lecture du postgis
# ogrListLayers(dsn) # Pour connaître la liste des PostGIS de la BDD
mapcanton <- readOGR(dsn = dsn, "canton")

# Sélection de la zone d'étude
mapcanton <- mapcanton[mapcanton@data$code_reg==reg,]

# Sélection des variables à cartographier

p_variable <- cbind("p_prairie","p_sth","p_sfp","p_mf","p_c")#Nom des variables élaborées RA calculées et jointes sur le PostGIS canton
l_variable <- cbind("Pourcentage Prairie","Pourcentage STH/SAU", "Pourcentage SFP/SAU", "Pourcentage MFL/SAU","Pourcentage C/SAU")# Nom des labels associés aux variables à cartographier. Vecteur utilisé pour les titres des cartes
period <- c("1979","1988","2000","2010") # Années des différents recencements agricoles
nclasse <- 5
style_classe <- "quantile"#"pretty"#"jenks" # Nombre de classe pour cartographier les variables

# Fonction pour gérer la légende 
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))# + theme(legend.position="bottom")
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

# Boucles pour cartographier chaque variable à chaque période de temps étudiée
cpt <- 0
p <- list()
for(v in p_variable){
  cpt <- cpt + 1
  print(v)
  
  cpt2 <- 0
  for(i in period){
    cpt2 <- cpt2 + 1
    p_variableRA <- paste(p_variable[cpt],i,sep="")
    l_variableRA <- l_variable[cpt]
    print(p_variableRA)
    
    # ggplot2
    gpclibPermit()
    carto <- fortify(mapcanton, region="id_geofla")

    # Jointure et changement de nom
    carto <- merge(carto, mapcanton@data[,c("id_geofla",p_variableRA)], by.x="id", by.y="id_geofla")
    colnames(carto)[8] <- "fill"
  
    if(cpt2==1){
      # Classement (pour faciliter l'interprétation, voir pour obtenir une même classe de valeur par période pour les 4 cartes)
      # Extraction de la légende (en horizontal) # Se débrouiller pour partir de 0/Problème dans le classement lorsque l'on part de 1979...certaines valeurs ne sont plus représentées avec les autres années
      classe_valeur <- round(classIntervals(carto[,"fill"],n=nclasse,style=style_classe,digits=2,na.rm=TRUE)[[2]],0)
      classe_valeur[1] <- 0
      classe_valeur[nclasse+1] <- 100
      carto[,"fill"] <- cut(carto[,"fill"] ,breaks = data.frame(classe_valeur)[,1],include.lowest=T)  
      p1 <- ggplot(carto, aes(x=long, y=lat)) +  geom_polygon(data=carto, aes(group=group, fill=fill)) + scale_fill_brewer(palette = "Spectral",name=paste(l_variableRA,sep=""),guide = guide_legend(reverse=FALSE,nrow=1))+theme(legend.position="bottom")#+guides(colour = guide_legend(nrow = 1))
      plotLegend = g_legend(p1)  
    }else{
      carto[,"fill"] <- cut(carto[,"fill"] ,breaks = data.frame(classe_valeur)[,1],include.lowest=T)
    }

    # Création de la carte (voir le label de la figure)
    p[[i]] <- ggplot(carto, aes(x=long, y=lat)) +
              geom_polygon(data=carto, aes(group=group, fill=fill)) +
              geom_path(data=carto, aes(x=long,y=lat,group=group),color="grey20")+
              scale_fill_brewer(palette = "Spectral",name=paste(l_variableRA,sep=""),guide = guide_legend(reverse=FALSE))+
              guides(fill=FALSE)+        
              #scale_fill_distiller(type="div",palette = "Spectral",limits = c(classe_valeur[1],classe_valeur[7]),guide="colourbar")+                     #scale_fill_distiller(palette = "Greens")+
              #scale_fill_distiller(type="div",name=paste(l_variableRA,sep=""), palette = "YlOrBr",breaks = classe_valeur,guide="legend")+
              #theme_bw()+
              #theme_minimal()+        
              #scale_x_continuous("", breaks=NULL)+
              #scale_y_continuous("", breaks=NULL)+
              coord_equal()+
              labs(title=i)
  }
  
  print("Sortie fichier")

  lwidth = sum(plotLegend$width)
  combinedPlots <- arrangeGrob(p[[1]],p[[2]],p[[3]],p[[4]],nrow=2)
  
  tt <- grid.arrange(combinedPlots,plotLegend,nrow=2,heights=c(10, 1))
  ggsave(tt, file = paste("map_",reg,"_",v,".png",sep=""), width = 10, height = 10)  
}
```






```{r,highlight=TRUE,eval=FALSE}
# Lecture de la table de travail
reg <- "54|23|83|25"

reg <- "26|23|83|54|74|52|53|25|74"

period <- c("1970","1979","1988","2000","2010") # Années des différents recencements agricoles

#melted.RA <- sqlQuery(loc,paste("select * from ra.melted_RA where code_reg similar to '",reg,"'",sep=""))
melted.RA <- sqlQuery(loc,paste("select * from ra.melted_RA where code_reg similar to '",reg,"'",sep=""))

melted.RA <- melted.RA[complete.cases(melted.RA),]


p_variable <- cbind("p_prairie","p_sth","p_sfp")#,"p_mf")#,"p_c")

cpt <- 0
for(i in p_variable){
  cpt <- cpt + 1
  melted.RAsth <- melted.RA[melted.RA["variable"] == i,]
  melted.RAsth[,"annees"] <- as.factor(melted.RAsth[,"annees"])
  #melted.RAsth[,"code_reg"] <- as.factor(melted.RAsth[,"code_reg"])
  melted.RAsth[,"nom_region"] <- as.factor(melted.RAsth[,"nom_region"])
  
  p <- ggplot(melted.RAsth) +
            geom_boxplot(aes(x=annees,y=value,col=nom_region))+
            geom_smooth(aes(x=as.integer(annees),y=value,color=nom_region,fill=nom_region),method=loess)+
            scale_x_discrete("Années")+scale_y_continuous("Pourcentage")+labs(title=i)+
            theme(plot.title = element_text(size = 14, face = "bold"), 
                  text = element_text(size = 12),
                  axis.title = element_text(face="bold"),
                  axis.text.x=element_text(size = 11))
  
  ggsave(p,file = paste("evolregion",i,".png",sep=""), width = 15, height = 10)  
  }
  
  #tt <- do.call("grid.arrange",p)
  #ggsave(tt, file = paste("map_",reg,"_",v,".png",sep=""), width = 10, height = 10)  
```




```{r,highlight=TRUE,eval=FALSE}
##################Autre méthode#######################

sth <- c("p_sth1979","p_sth1988","p_sth2000","p_sth2010")
sfp <- c("p_sfp1979","p_sfp1988","p_sfp2000","p_sfp2010")

pdf(paste("STH_SFP.pdf",sep=""),width=7, height=7)
boxplot(mapcanton@data[,sth],at = 1:4 - 0.15,col = "white",xlab="Années",ylab="% de SAU",boxwex = 0.15,xaxt = "n",ylim=c(0,100))
axis(1, at = 1:4, labels=c("1979","1988","2000","2010"))
boxplot(mapcanton@data[,sfp],boxwex = 0.15,at = 1:4 + 0.15,col = "grey",xaxt = "n",outline=FALSE,add=TRUE,axes=FALSE)
box()
legend("bottomleft",c("sth", "sfp"),fill = c("white", "grey"),bty="n")
dev.off()

summary(mapcanton@data$p_sth1979)
summary(mapcanton@data$p_sth1988)
summary(mapcanton@data$p_sth2000)
summary(mapcanton@data$p_sth2010)
```


## Exploration et fouille de données

```{r,highlight=TRUE,eval=FALSE}
# Pour l'exploration, on se basera sur les fichiers sources du RA (différent melted)

dsn <- "PG:dbname='sol_elevage' host='localhost' port='5432' user='jb'" # Configuration de la connexion vers le PostGIS
varia <- c("p_sth","p_sfp","p_prairie") # Variable à analyser 
period <- c("1979","1988","2000","2010") #Période de temps
id <- c("code_canton","code_reg") #Nom de l'identifiant

variable <- paste()

# Lecture du postgis
mapcanton <- readOGR(dsn = dsn, "canton")

sth <- c("p_sth1979","p_sth1988","p_sth2000","p_sth2010")
sfp <- c("p_sfp1979","p_sfp1988","p_sfp2000","p_sfp2010")

mapcanton.active <- mapcanton@data[,c("corgox_med9094","corgox_med9599","corgox_med0004","corgox_med0509",sth,sfp)]
res.pca <- PCA(mapcanton.active, graph = FALSE)
fviz_pca_var(res.pca)

#fviz_pca_var(res.pca, col.var="cos2") +
#scale_color_gradient2(low="white", mid="blue", 
                    #high="red", midpoint=0.5) + theme_minimal()
```