---
title: "Traitement des données de la BDAT"
author: "Jean-Baptiste Paroissien"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 10
    fig_height: 10
    dev: png
    md_extensions: +autolink_bare_uris+hard_line_breaks+header_attributes+line_blocks+table_captions
---

```{r setup, include=FALSE,eval=TRUE}
# Importation des paramètres de travail
source("/media/sf_GIS_ED/Dev/Scripts/master/Fonctions/R/importparametres.R")
repmaster <- "/media/sf_GIS_ED/Dev/Scripts/master/"
importparametres(repmaster=repmaster,repdata="/media/sf_GIS_ED/Dev/Data/",dsn="PG:dbname='sol_elevage' host='localhost' port='5432' user='jb'")
```

```{r, tidy=FALSE,eval=TRUE}
Sys.Date()
sessionInfo()
```

# Objectifs

L'objectif de ce travail est de calcul une valeur médiane du taux d'argile à l'échelle cantonale.

# Intégration des données de la BDAT vers la table `dm_vecteurs.canton`

## Intégration de la médiane des teneurs en carbone organique par canton
```{r,highlight=TRUE,eval=FALSE}
# Paramètres
table_dm <- "dm_vecteurs.canton" # Nom de la table pour rassembler les calculs (vers le schéma dm_vecteurs)
period <- c("9094","9599","0004","0509","1014")
schema <- "bdat"

for(i in period){
  var_variable <- paste("corgox_medequi",i,sep="")
  tableBDAT <- paste("bdat_canton_corgequiv",i,sep="")
  
  sqlQuery(loc,paste("alter table ",table_dm,"
                      drop column if exists ",var_variable,sep=""))
  
  sqlQuery(loc,paste("alter table ",table_dm,"
                      add column ",var_variable," numeric;
                      update ",table_dm,"
                      SET ",var_variable," = s1.med from(
                      select med,canton
                      from ",schema,".",tableBDAT,") as s1
                      where ",table_dm,".code_canton=s1.canton::text",sep=""))
  
  # Ajout d'un commentaire sur la nouvelle colonne crée
  print(sqlQuery(loc,paste("
  COMMENT ON COLUMN ",table_dm,".",var_variable," IS \'Médiane des teneurs en carbone organique après ré-échantillonnage pour la période ",i,".\';",sep="")))
}
```

## Intégration des effectifs par période

```{r,highlight=TRUE,eval=FALSE}
# Paramètres
table_dm <- "dm_vecteurs.canton" # Nom de la table pour rassembler les calculs (vers le schéma dm_vecteurs)
period <- c("9094","9599","0004","0509","1014")
schema <- "bdat"

for(i in period){
  var_variable <- paste("eff",i,sep="")
  tableBDAT <- paste("bdat_canton_corgequiv",i,sep="")
  
  sqlQuery(loc,paste("alter table ",table_dm,"
                      drop column if exists ",var_variable,sep=""))
  
  sqlQuery(loc,paste("alter table ",table_dm,"
                      add column ",var_variable," numeric;
                      update ",table_dm,"
                      SET ",var_variable," = s1.eff from(
                      select eff,canton
                      from ",schema,".",tableBDAT,") as s1
                      where ",table_dm,".code_canton=s1.canton::text",sep=""))
  
  # Ajout d'un commentaire sur la nouvelle colonne crée
  print(sqlQuery(loc,paste("
  COMMENT ON COLUMN ",table_dm,".",var_variable," IS \'Nombre d\''effectif par canton",i,".\';",sep="")))
}
```



