---
title: "Conversion de la base postgresql/postgis vers sqlite/spatialite"
author: "Jean-Baptiste Paroissien"
date: "25/01/2017"
output:
  html_notebook:
    toc: true
    fig_caption: true
    highlight: zenburn
    number_sections: yes
    theme: spacelab
---

```{r setup, include=FALSE}
# Importation des paramètres de travail
source("/media/sf_GIS_ED/Dev/Scripts/master/Fonctions/R/importparametres.R")
repmaster <- "/media/sf_GIS_ED/Dev/Scripts/master/"
repdata <- "/media/sf_GIS_ED/Dev/Data/"
importparametres(repmaster=repmaster,repdata=repdata,dsn="PG:dbname='sol_elevage' host='localhost' port='5432' user='jb'")
```

# Objectifs

Voir la procédure selon :
http://manuelvanrijn.nl/blog/2012/01/18/convert-postgresql-to-sqlite/

ici, il y a un script python à voir de plus près:
https://www.jjude.com/pg-to-sqlite/

# Conversion 


```{r, engine='bash',highlight=TRUE,eval=FALSE}
sudo -i -u postgres
postgres=# CREATE USER jb;
postgres-# ALTER ROLE jb WITH CREATEDB;
postgres=# CREATE DATABASE SOL_ELEVAGE OWNER jb;
postgres-# ALTER USER jb WITH ENCRYPTED PASSWORD '******';
postgres=# CREATE DATABASE sol_elevage OWNER jb;
--Installation de l'extension postgis--
-- Enable PostGIS (includes raster)
CREATE EXTENSION postgis;
-- Enable Topology
CREATE EXTENSION postgis_topology;
-- Enable PostGIS Advanced 3D 
-- and other geoprocessing algorithms
-- sfcgal not available with all distributions
CREATE EXTENSION postgis_sfcgal;
-- fuzzy matching needed for Tiger
CREATE EXTENSION fuzzystrmatch;
-- rule based standardizer
CREATE EXTENSION address_standardizer;
-- example rule data set
CREATE EXTENSION address_standardizer_data_us;
-- Enable US Tiger Geocoder
CREATE EXTENSION postgis_tiger_geocoder;
CREATE EXTENSION postgis_sfcgal;
```    
Configuration du fichier `\etc\odbc.ini` pour se connecter à la base avec R grâce au paquet RODBC.

```{r, engine='bash',highlight=TRUE,eval=FALSE}
[ODBC]
InstallDir = /usr/lib

[solelevage]
Driver = /usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
Database = sol_elevage
Servername = localhost
Username = jb	
Password = *******
Port=5432
Protocol = 8.1
ReadOnly = 0
```


